### ISSUE TITLE
Direct Message

### ISSUE THREAD

**Issue by HasanKarasahin** [M1n007/node-insta-web-api#1]
Hello everyone! How to send message on this API? Thank you :)

**Comment by AkunBlackhat** [comment]
> Hello everyone! How to send message on this API? Thank you :)

for now you cannot send direct messages with this module.

U can send direct message with instagram-private-api https://github.com/dilame/instagram-private-api/issues/792

**Comment by M1n007** [comment]
Feature direct message added using client from [dilame/instagram-private-api](https://github.com/dilame/instagram-private-api)
